version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: evoicebot_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    container_name: evoicebot_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py migrate django_celery_beat &&
             python manage.py migrate django_celery_results &&
             python manage.py setup_celery &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=evoicebot.settings
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    build: .
    container_name: evoicebot_celery
    command: celery -A evoicebot worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=evoicebot.settings
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: evoicebot_celery_beat
    command: celery -A evoicebot beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=evoicebot.settings
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    restart: unless-stopped

  flower:
    build: .
    container_name: evoicebot_flower
    command: celery -A evoicebot flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=evoicebot.settings
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  default:
    name: evoicebot_network