from django.urls import path

from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('app/login/', login, name='login'),
    path('app/register/', register, name='register'),
    path('app/logout/', logout, name='logout'),
    path('app/profile/', profile, name='profile'),
    path('app/profile/edit/', edit_profile, name='edit_profile'),
    path('app/profile/change-password/', change_password, name='change_password'),
    path('app/dashboard/', dashboard, name='dashboard'),
    path('app/dashboard/teams/', team_list, name='team_list'),
    path('app/dashboard/teams/<uuid:uuid>/', team_detail, name='team_detail'),
    path('app/dashboard/teams/<uuid:uuid>/edit/', edit_team, name='edit_team'),
    path('app/dashboard/teams/<uuid:uuid>/members/', manage_team_members, name='manage_team_members'),
    path('app/dashboard/teams/create/', create_team, name='create_team'),
    path('app/dashboard/projects/', project_list, name='project_list'),
    path('app/dashboard/projects/<uuid:uuid>/', project_detail, name='project_detail'),
    path('app/dashboard/projects/create/', create_project, name='create_project'),
    path('app/dashboard/projects/<uuid:uuid>/edit/', edit_project, name='edit_project'),
    path('app/dashboard/projects/<uuid:uuid>/delete/', delete_project, name='delete_project'),
    path('app/dashboard/documents/', document_list, name='document_list'),
    path('app/dashboard/documents/<uuid:uuid>/', document_detail, name='document_detail'),
    path('app/dashboard/documents/create/', create_document, name='create_document'),
    path('app/dashboard/documents/<uuid:uuid>/edit/', edit_document, name='edit_document'),
    path('app/dashboard/documents/<uuid:uuid>/delete/', delete_document, name='delete_document'),
    path('app/dashboard/voice-calls/', voice_call_list, name='voice_call_list'),
    path('app/dashboard/voice-calls/<int:call_id>/', voice_call_detail, name='voice_call_detail'),
    path('app/dashboard/voice-calls/make/', make_voice_call, name='make_voice_call'),
    path('app/dashboard/voice-calls/<int:call_id>/update-status/', update_call_status, name='update_call_status'),
    path('app/dashboard/voice-calls/<int:call_id>/end/', end_call, name='end_call'),
    path('app/dashboard/documents/<uuid:document_uuid>/voice-notification/', document_voice_notification,
         name='document_voice_notification'),
    path('twilio/twiml/', twilio_twiml, name='twilio_twiml'),
    path('twilio/gather/', twilio_gather, name='twilio_gather'),
    path('twilio/no-input/', twilio_no_input, name='twilio_no_input'),
    path('twilio/status-callback/', twilio_status_callback, name='twilio_status_callback'),
]
