# Generated by Django 5.2 on 2025-04-21 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0005_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenty'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Format pliku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='evoicebot_app.project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='document',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='evoicebot_app.team', verbose_name='Zespół'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='document',
            name='users',
            field=models.ManyToManyField(related_name='documents', to='evoicebot_app.userprofile', verbose_name='Użytkownicy'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
