# Generated by Django 5.2 on 2025-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0006_alter_document_options_remove_document_file_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis AI'),
        ),
    ]
