# Generated by Django 5.2 on 2025-04-24 18:30

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0007_document_ai_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='documents/', verbose_name='Plik'),
        ),
    ]
