# Generated by Django 5.2 on 2025-04-28 15:51

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0008_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_audio',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='documents/audio/', verbose_name='Audio AI'),
        ),
    ]
