# Generated by Django 5.2 on 2025-04-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0009_document_ai_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Termin ważności'),
        ),
    ]
