# Generated by Django 5.1.10 on 2025-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0010_document_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='Analiza AI'),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_audio_script',
            field=models.TextField(blank=True, null=True, verbose_name='Skrypt Audio AI'),
        ),
        migrations.AddField(
            model_name='document',
            name='workflow_plan',
            field=models.TextField(blank=True, null=True, verbose_name='Plan Workflow'),
        ),
    ]
