# Generated by Django 5.1.10 on 2025-06-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0011_document_ai_analysis_document_ai_audio_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ai_audio_script',
        ),
        migrations.RemoveField(
            model_name='document',
            name='workflow_plan',
        ),
    ]
