# Generated by Django 5.1.10 on 2025-06-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0012_remove_document_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100, unique=True, verbose_name='Twilio SID')),
                ('to_number', models.CharField(max_length=20, verbose_name='Numer odbiorcy')),
                ('from_number', models.CharField(max_length=20, verbose_name='Numer nadawcy')),
                ('message_text', models.TextField(verbose_name='Treść wiadomości')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='initiated', max_length=20, verbose_name='Status')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Czas trwania (sekundy)')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Koszt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data odebrania')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('confirmation_received', models.BooleanField(default=False, verbose_name='Potwierdzenie otrzymane')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='evoicebot_app.document', verbose_name='Dokument')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='evoicebot_app.userprofile', verbose_name='Profil użytkownika')),
            ],
            options={
                'verbose_name': 'Połączenie głosowe',
                'verbose_name_plural': 'Połączenia głosowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
