# Generated by Django 5.1.10 on 2025-06-07 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoicebot_app', '0013_voicecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='call_attempts',
            field=models.IntegerField(default=0, verbose_name='Call attempts'),
        ),
        migrations.AddField(
            model_name='document',
            name='call_message_listened',
            field=models.BooleanField(default=False, verbose_name='Call message listened'),
        ),
        migrations.AddField(
            model_name='document',
            name='call_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Call reminder sent'),
        ),
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data wygaśnięcia'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram File ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GCS file path'),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_uploaded',
            field=models.BooleanField(default=False, verbose_name='GCS uploaded'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last call date'),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='document',
            name='sms_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='SMS reminder sent'),
        ),
        migrations.AddField(
            model_name='document',
            name='telegram_reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Telegram reminder sent'),
        ),
        migrations.AddField(
            model_name='document',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_documents', to='evoicebot_app.userprofile', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
